window.esdocSearchIndex = [
  [
    "chainabstractionlayer/src/providers/bitcoin/bitcoinledgerprovider.js~bitcoinledgerprovider",
    "class/src/providers/bitcoin/BitcoinLedgerProvider.js~BitcoinLedgerProvider.html",
    "<span>BitcoinLedgerProvider</span> <span class=\"search-result-import-path\">chainabstractionlayer/src/providers/bitcoin/BitcoinLedgerProvider.js</span>",
    "class"
  ],
  [
    "chainabstractionlayer/src/providers/bitcoin/bitcoinrpcprovider.js~bitcoinrpcprovider",
    "class/src/providers/bitcoin/BitcoinRPCProvider.js~BitcoinRPCProvider.html",
    "<span>BitcoinRPCProvider</span> <span class=\"search-result-import-path\">chainabstractionlayer/src/providers/bitcoin/BitcoinRPCProvider.js</span>",
    "class"
  ],
  [
    "chainabstractionlayer/src/index.js~chainabstractionlayer",
    "class/src/index.js~ChainAbstractionLayer.html",
    "<span>ChainAbstractionLayer</span> <span class=\"search-result-import-path\">chainabstractionlayer/src/index.js</span>",
    "class"
  ],
  [
    "chainabstractionlayer/src/providers/ethereum/ethereumledgerprovider.js~ethereumledgerprovider",
    "class/src/providers/ethereum/EthereumLedgerProvider.js~EthereumLedgerProvider.html",
    "<span>EthereumLedgerProvider</span> <span class=\"search-result-import-path\">chainabstractionlayer/src/providers/ethereum/EthereumLedgerProvider.js</span>",
    "class"
  ],
  [
    "chainabstractionlayer/src/providers/ethereum/ethereummetamaskprovider.js~ethereummetamaskprovider",
    "class/src/providers/ethereum/EthereumMetaMaskProvider.js~EthereumMetaMaskProvider.html",
    "<span>EthereumMetaMaskProvider</span> <span class=\"search-result-import-path\">chainabstractionlayer/src/providers/ethereum/EthereumMetaMaskProvider.js</span>",
    "class"
  ],
  [
    "chainabstractionlayer/src/providers/ethereum/ethereumrpcprovider.js~ethereumrpcprovider",
    "class/src/providers/ethereum/EthereumRPCProvider.js~EthereumRPCProvider.html",
    "<span>EthereumRPCProvider</span> <span class=\"search-result-import-path\">chainabstractionlayer/src/providers/ethereum/EthereumRPCProvider.js</span>",
    "class"
  ],
  [
    "chainabstractionlayer/src/providers/jsonrpchelper.js~praseresponse",
    "function/index.html#static-function-praseResponse",
    "<span>praseResponse</span> <span class=\"search-result-import-path\">chainabstractionlayer/src/providers/JsonRpcHelper.js</span>",
    "function"
  ],
  [
    "chainabstractionlayer/src/providers/jsonrpchelper.js~preparerequest",
    "function/index.html#static-function-prepareRequest",
    "<span>prepareRequest</span> <span class=\"search-result-import-path\">chainabstractionlayer/src/providers/JsonRpcHelper.js</span>",
    "function"
  ],
  [
    "src/.external-ecmascript.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "src/.external-ecmascript.js~Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "src/.external-ecmascript.js~ArrayBuffer",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~Boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "src/.external-ecmascript.js~DataView",
    "external"
  ],
  [
    "src/.external-ecmascript.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "src/.external-ecmascript.js~Date",
    "external"
  ],
  [
    "src/.external-ecmascript.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "src/.external-ecmascript.js~Error",
    "external"
  ],
  [
    "src/.external-ecmascript.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "src/.external-ecmascript.js~EvalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "src/.external-ecmascript.js~Float32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "src/.external-ecmascript.js~Float64Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~Function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "src/.external-ecmascript.js~Generator",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "src/.external-ecmascript.js~GeneratorFunction",
    "external"
  ],
  [
    "src/.external-ecmascript.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "src/.external-ecmascript.js~Infinity",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "src/.external-ecmascript.js~Int16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "src/.external-ecmascript.js~Int32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "src/.external-ecmascript.js~Int8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "src/.external-ecmascript.js~InternalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "src/.external-ecmascript.js~JSON",
    "external"
  ],
  [
    "src/.external-ecmascript.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "src/.external-ecmascript.js~Map",
    "external"
  ],
  [
    "src/.external-ecmascript.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "src/.external-ecmascript.js~NaN",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~Number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~Object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "src/.external-ecmascript.js~Promise",
    "external"
  ],
  [
    "src/.external-ecmascript.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "src/.external-ecmascript.js~Proxy",
    "external"
  ],
  [
    "src/.external-ecmascript.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "src/.external-ecmascript.js~RangeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "src/.external-ecmascript.js~ReferenceError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "src/.external-ecmascript.js~Reflect",
    "external"
  ],
  [
    "src/.external-ecmascript.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "src/.external-ecmascript.js~RegExp",
    "external"
  ],
  [
    "src/.external-ecmascript.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "src/.external-ecmascript.js~Set",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~String",
    "external"
  ],
  [
    "src/.external-ecmascript.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "src/.external-ecmascript.js~Symbol",
    "external"
  ],
  [
    "src/.external-ecmascript.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "src/.external-ecmascript.js~SyntaxError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "src/.external-ecmascript.js~TypeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "src/.external-ecmascript.js~URIError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "src/.external-ecmascript.js~Uint16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "src/.external-ecmascript.js~Uint32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "src/.external-ecmascript.js~Uint8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "src/.external-ecmascript.js~Uint8ClampedArray",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "src/.external-ecmascript.js~WeakMap",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "src/.external-ecmascript.js~WeakSet",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "src/.external-ecmascript.js~null",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~string",
    "external"
  ],
  [
    "src/.external-ecmascript.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "src/.external-ecmascript.js~undefined",
    "external"
  ],
  [
    "src/index.js",
    "file/src/index.js.html",
    "src/index.js",
    "file"
  ],
  [
    "src/index.js~chainabstractionlayer#_checkmethod",
    "class/src/index.js~ChainAbstractionLayer.html#instance-method-_checkMethod",
    "src/index.js~ChainAbstractionLayer#_checkMethod",
    "method"
  ],
  [
    "src/index.js~chainabstractionlayer#addprovider",
    "class/src/index.js~ChainAbstractionLayer.html#instance-method-addProvider",
    "src/index.js~ChainAbstractionLayer#addProvider",
    "method"
  ],
  [
    "src/index.js~chainabstractionlayer#constructor",
    "class/src/index.js~ChainAbstractionLayer.html#instance-constructor-constructor",
    "src/index.js~ChainAbstractionLayer#constructor",
    "method"
  ],
  [
    "src/index.js~chainabstractionlayer#generateblock",
    "class/src/index.js~ChainAbstractionLayer.html#instance-method-generateBlock",
    "src/index.js~ChainAbstractionLayer#generateBlock",
    "method"
  ],
  [
    "src/index.js~chainabstractionlayer#getaddresses",
    "class/src/index.js~ChainAbstractionLayer.html#instance-method-getAddresses",
    "src/index.js~ChainAbstractionLayer#getAddresses",
    "method"
  ],
  [
    "src/index.js~chainabstractionlayer#getblockbyhash",
    "class/src/index.js~ChainAbstractionLayer.html#instance-method-getBlockByHash",
    "src/index.js~ChainAbstractionLayer#getBlockByHash",
    "method"
  ],
  [
    "src/index.js~chainabstractionlayer#getblockbynumber",
    "class/src/index.js~ChainAbstractionLayer.html#instance-method-getBlockByNumber",
    "src/index.js~ChainAbstractionLayer#getBlockByNumber",
    "method"
  ],
  [
    "src/index.js~chainabstractionlayer#getblockheight",
    "class/src/index.js~ChainAbstractionLayer.html#instance-method-getBlockHeight",
    "src/index.js~ChainAbstractionLayer#getBlockHeight",
    "method"
  ],
  [
    "src/index.js~chainabstractionlayer#getrawtransactionbyhash",
    "class/src/index.js~ChainAbstractionLayer.html#instance-method-getRawTransactionByHash",
    "src/index.js~ChainAbstractionLayer#getRawTransactionByHash",
    "method"
  ],
  [
    "src/index.js~chainabstractionlayer#gettransactionbyhash",
    "class/src/index.js~ChainAbstractionLayer.html#instance-method-getTransactionByHash",
    "src/index.js~ChainAbstractionLayer#getTransactionByHash",
    "method"
  ],
  [
    "src/index.js~chainabstractionlayer#provider",
    "class/src/index.js~ChainAbstractionLayer.html#instance-member-provider",
    "src/index.js~ChainAbstractionLayer#provider",
    "member"
  ],
  [
    "src/index.js~chainabstractionlayer#sendtransaction",
    "class/src/index.js~ChainAbstractionLayer.html#instance-method-sendTransaction",
    "src/index.js~ChainAbstractionLayer#sendTransaction",
    "method"
  ],
  [
    "src/index.js~chainabstractionlayer#signmessage",
    "class/src/index.js~ChainAbstractionLayer.html#instance-method-signMessage",
    "src/index.js~ChainAbstractionLayer#signMessage",
    "method"
  ],
  [
    "src/index.js~chainabstractionlayer#validateblock",
    "class/src/index.js~ChainAbstractionLayer.html#instance-member-validateBlock",
    "src/index.js~ChainAbstractionLayer#validateBlock",
    "member"
  ],
  [
    "src/index.js~chainabstractionlayer#validatetransaction",
    "class/src/index.js~ChainAbstractionLayer.html#instance-member-validateTransaction",
    "src/index.js~ChainAbstractionLayer#validateTransaction",
    "member"
  ],
  [
    "src/index.js~chainabstractionlayer#version",
    "class/src/index.js~ChainAbstractionLayer.html#instance-member-version",
    "src/index.js~ChainAbstractionLayer#version",
    "member"
  ],
  [
    "src/providers/jsonrpchelper.js",
    "file/src/providers/JsonRpcHelper.js.html",
    "src/providers/JsonRpcHelper.js",
    "file"
  ],
  [
    "src/providers/bitcoin/bitcoinledgerprovider.js",
    "file/src/providers/bitcoin/BitcoinLedgerProvider.js.html",
    "src/providers/bitcoin/BitcoinLedgerProvider.js",
    "file"
  ],
  [
    "src/providers/bitcoin/bitcoinledgerprovider.js~bitcoinledgerprovider#_connecttoledger",
    "class/src/providers/bitcoin/BitcoinLedgerProvider.js~BitcoinLedgerProvider.html#instance-method-_connectToLedger",
    "src/providers/bitcoin/BitcoinLedgerProvider.js~BitcoinLedgerProvider#_connectToLedger",
    "method"
  ],
  [
    "src/providers/bitcoin/bitcoinledgerprovider.js~bitcoinledgerprovider#_derivationpath",
    "class/src/providers/bitcoin/BitcoinLedgerProvider.js~BitcoinLedgerProvider.html#instance-member-_derivationPath",
    "src/providers/bitcoin/BitcoinLedgerProvider.js~BitcoinLedgerProvider#_derivationPath",
    "member"
  ],
  [
    "src/providers/bitcoin/bitcoinledgerprovider.js~bitcoinledgerprovider#_ledgerbtc",
    "class/src/providers/bitcoin/BitcoinLedgerProvider.js~BitcoinLedgerProvider.html#instance-member-_ledgerBtc",
    "src/providers/bitcoin/BitcoinLedgerProvider.js~BitcoinLedgerProvider#_ledgerBtc",
    "member"
  ],
  [
    "src/providers/bitcoin/bitcoinledgerprovider.js~bitcoinledgerprovider#_updatederivationpath",
    "class/src/providers/bitcoin/BitcoinLedgerProvider.js~BitcoinLedgerProvider.html#instance-method-_updateDerivationPath",
    "src/providers/bitcoin/BitcoinLedgerProvider.js~BitcoinLedgerProvider#_updateDerivationPath",
    "method"
  ],
  [
    "src/providers/bitcoin/bitcoinledgerprovider.js~bitcoinledgerprovider#constructor",
    "class/src/providers/bitcoin/BitcoinLedgerProvider.js~BitcoinLedgerProvider.html#instance-constructor-constructor",
    "src/providers/bitcoin/BitcoinLedgerProvider.js~BitcoinLedgerProvider#constructor",
    "method"
  ],
  [
    "src/providers/bitcoin/bitcoinledgerprovider.js~bitcoinledgerprovider#getaddresses",
    "class/src/providers/bitcoin/BitcoinLedgerProvider.js~BitcoinLedgerProvider.html#instance-method-getAddresses",
    "src/providers/bitcoin/BitcoinLedgerProvider.js~BitcoinLedgerProvider#getAddresses",
    "method"
  ],
  [
    "src/providers/bitcoin/bitcoinledgerprovider.js~bitcoinledgerprovider#signmessage",
    "class/src/providers/bitcoin/BitcoinLedgerProvider.js~BitcoinLedgerProvider.html#instance-method-signMessage",
    "src/providers/bitcoin/BitcoinLedgerProvider.js~BitcoinLedgerProvider#signMessage",
    "method"
  ],
  [
    "src/providers/bitcoin/bitcoinrpcprovider.js",
    "file/src/providers/bitcoin/BitcoinRPCProvider.js.html",
    "src/providers/bitcoin/BitcoinRPCProvider.js",
    "file"
  ],
  [
    "src/providers/bitcoin/bitcoinrpcprovider.js~bitcoinrpcprovider#_decoderawtransaction",
    "class/src/providers/bitcoin/BitcoinRPCProvider.js~BitcoinRPCProvider.html#instance-method-_decodeRawTransaction",
    "src/providers/bitcoin/BitcoinRPCProvider.js~BitcoinRPCProvider#_decodeRawTransaction",
    "method"
  ],
  [
    "src/providers/bitcoin/bitcoinrpcprovider.js~bitcoinrpcprovider#_rpc",
    "class/src/providers/bitcoin/BitcoinRPCProvider.js~BitcoinRPCProvider.html#instance-method-_rpc",
    "src/providers/bitcoin/BitcoinRPCProvider.js~BitcoinRPCProvider#_rpc",
    "method"
  ],
  [
    "src/providers/bitcoin/bitcoinrpcprovider.js~bitcoinrpcprovider#axios",
    "class/src/providers/bitcoin/BitcoinRPCProvider.js~BitcoinRPCProvider.html#instance-member-axios",
    "src/providers/bitcoin/BitcoinRPCProvider.js~BitcoinRPCProvider#axios",
    "member"
  ],
  [
    "src/providers/bitcoin/bitcoinrpcprovider.js~bitcoinrpcprovider#constructor",
    "class/src/providers/bitcoin/BitcoinRPCProvider.js~BitcoinRPCProvider.html#instance-constructor-constructor",
    "src/providers/bitcoin/BitcoinRPCProvider.js~BitcoinRPCProvider#constructor",
    "method"
  ],
  [
    "src/providers/bitcoin/bitcoinrpcprovider.js~bitcoinrpcprovider#generateblock",
    "class/src/providers/bitcoin/BitcoinRPCProvider.js~BitcoinRPCProvider.html#instance-method-generateBlock",
    "src/providers/bitcoin/BitcoinRPCProvider.js~BitcoinRPCProvider#generateBlock",
    "method"
  ],
  [
    "src/providers/bitcoin/bitcoinrpcprovider.js~bitcoinrpcprovider#getblockbyhash",
    "class/src/providers/bitcoin/BitcoinRPCProvider.js~BitcoinRPCProvider.html#instance-method-getBlockByHash",
    "src/providers/bitcoin/BitcoinRPCProvider.js~BitcoinRPCProvider#getBlockByHash",
    "method"
  ],
  [
    "src/providers/bitcoin/bitcoinrpcprovider.js~bitcoinrpcprovider#getblockbynumber",
    "class/src/providers/bitcoin/BitcoinRPCProvider.js~BitcoinRPCProvider.html#instance-method-getBlockByNumber",
    "src/providers/bitcoin/BitcoinRPCProvider.js~BitcoinRPCProvider#getBlockByNumber",
    "method"
  ],
  [
    "src/providers/bitcoin/bitcoinrpcprovider.js~bitcoinrpcprovider#getrawtransactionbyhash",
    "class/src/providers/bitcoin/BitcoinRPCProvider.js~BitcoinRPCProvider.html#instance-method-getRawTransactionByHash",
    "src/providers/bitcoin/BitcoinRPCProvider.js~BitcoinRPCProvider#getRawTransactionByHash",
    "method"
  ],
  [
    "src/providers/bitcoin/bitcoinrpcprovider.js~bitcoinrpcprovider#gettransactionbyhash",
    "class/src/providers/bitcoin/BitcoinRPCProvider.js~BitcoinRPCProvider.html#instance-method-getTransactionByHash",
    "src/providers/bitcoin/BitcoinRPCProvider.js~BitcoinRPCProvider#getTransactionByHash",
    "method"
  ],
  [
    "src/providers/ethereum/ethereumledgerprovider.js",
    "file/src/providers/ethereum/EthereumLedgerProvider.js.html",
    "src/providers/ethereum/EthereumLedgerProvider.js",
    "file"
  ],
  [
    "src/providers/ethereum/ethereumledgerprovider.js~ethereumledgerprovider#_connecttoledger",
    "class/src/providers/ethereum/EthereumLedgerProvider.js~EthereumLedgerProvider.html#instance-method-_connectToLedger",
    "src/providers/ethereum/EthereumLedgerProvider.js~EthereumLedgerProvider#_connectToLedger",
    "method"
  ],
  [
    "src/providers/ethereum/ethereumledgerprovider.js~ethereumledgerprovider#_derivationpath",
    "class/src/providers/ethereum/EthereumLedgerProvider.js~EthereumLedgerProvider.html#instance-member-_derivationPath",
    "src/providers/ethereum/EthereumLedgerProvider.js~EthereumLedgerProvider#_derivationPath",
    "member"
  ],
  [
    "src/providers/ethereum/ethereumledgerprovider.js~ethereumledgerprovider#_ledgereth",
    "class/src/providers/ethereum/EthereumLedgerProvider.js~EthereumLedgerProvider.html#instance-member-_ledgerEth",
    "src/providers/ethereum/EthereumLedgerProvider.js~EthereumLedgerProvider#_ledgerEth",
    "member"
  ],
  [
    "src/providers/ethereum/ethereumledgerprovider.js~ethereumledgerprovider#_updatederivationpath",
    "class/src/providers/ethereum/EthereumLedgerProvider.js~EthereumLedgerProvider.html#instance-method-_updateDerivationPath",
    "src/providers/ethereum/EthereumLedgerProvider.js~EthereumLedgerProvider#_updateDerivationPath",
    "method"
  ],
  [
    "src/providers/ethereum/ethereumledgerprovider.js~ethereumledgerprovider#constructor",
    "class/src/providers/ethereum/EthereumLedgerProvider.js~EthereumLedgerProvider.html#instance-constructor-constructor",
    "src/providers/ethereum/EthereumLedgerProvider.js~EthereumLedgerProvider#constructor",
    "method"
  ],
  [
    "src/providers/ethereum/ethereumledgerprovider.js~ethereumledgerprovider#getaddresses",
    "class/src/providers/ethereum/EthereumLedgerProvider.js~EthereumLedgerProvider.html#instance-method-getAddresses",
    "src/providers/ethereum/EthereumLedgerProvider.js~EthereumLedgerProvider#getAddresses",
    "method"
  ],
  [
    "src/providers/ethereum/ethereumledgerprovider.js~ethereumledgerprovider#signmessage",
    "class/src/providers/ethereum/EthereumLedgerProvider.js~EthereumLedgerProvider.html#instance-method-signMessage",
    "src/providers/ethereum/EthereumLedgerProvider.js~EthereumLedgerProvider#signMessage",
    "method"
  ],
  [
    "src/providers/ethereum/ethereummetamaskprovider.js",
    "file/src/providers/ethereum/EthereumMetaMaskProvider.js.html",
    "src/providers/ethereum/EthereumMetaMaskProvider.js",
    "file"
  ],
  [
    "src/providers/ethereum/ethereummetamaskprovider.js~ethereummetamaskprovider#_metamaskprovider",
    "class/src/providers/ethereum/EthereumMetaMaskProvider.js~EthereumMetaMaskProvider.html#instance-member-_metamaskProvider",
    "src/providers/ethereum/EthereumMetaMaskProvider.js~EthereumMetaMaskProvider#_metamaskProvider",
    "member"
  ],
  [
    "src/providers/ethereum/ethereummetamaskprovider.js~ethereummetamaskprovider#_tomm",
    "class/src/providers/ethereum/EthereumMetaMaskProvider.js~EthereumMetaMaskProvider.html#instance-method-_toMM",
    "src/providers/ethereum/EthereumMetaMaskProvider.js~EthereumMetaMaskProvider#_toMM",
    "method"
  ],
  [
    "src/providers/ethereum/ethereummetamaskprovider.js~ethereummetamaskprovider#constructor",
    "class/src/providers/ethereum/EthereumMetaMaskProvider.js~EthereumMetaMaskProvider.html#instance-constructor-constructor",
    "src/providers/ethereum/EthereumMetaMaskProvider.js~EthereumMetaMaskProvider#constructor",
    "method"
  ],
  [
    "src/providers/ethereum/ethereummetamaskprovider.js~ethereummetamaskprovider#getaddresses",
    "class/src/providers/ethereum/EthereumMetaMaskProvider.js~EthereumMetaMaskProvider.html#instance-method-getAddresses",
    "src/providers/ethereum/EthereumMetaMaskProvider.js~EthereumMetaMaskProvider#getAddresses",
    "method"
  ],
  [
    "src/providers/ethereum/ethereummetamaskprovider.js~ethereummetamaskprovider#sendtransaction",
    "class/src/providers/ethereum/EthereumMetaMaskProvider.js~EthereumMetaMaskProvider.html#instance-method-sendTransaction",
    "src/providers/ethereum/EthereumMetaMaskProvider.js~EthereumMetaMaskProvider#sendTransaction",
    "method"
  ],
  [
    "src/providers/ethereum/ethereummetamaskprovider.js~ethereummetamaskprovider#signmessage",
    "class/src/providers/ethereum/EthereumMetaMaskProvider.js~EthereumMetaMaskProvider.html#instance-method-signMessage",
    "src/providers/ethereum/EthereumMetaMaskProvider.js~EthereumMetaMaskProvider#signMessage",
    "method"
  ],
  [
    "src/providers/ethereum/ethereumrpcprovider.js",
    "file/src/providers/ethereum/EthereumRPCProvider.js.html",
    "src/providers/ethereum/EthereumRPCProvider.js",
    "file"
  ],
  [
    "src/providers/ethereum/ethereumrpcprovider.js~ethereumrpcprovider#_rpc",
    "class/src/providers/ethereum/EthereumRPCProvider.js~EthereumRPCProvider.html#instance-method-_rpc",
    "src/providers/ethereum/EthereumRPCProvider.js~EthereumRPCProvider#_rpc",
    "method"
  ],
  [
    "src/providers/ethereum/ethereumrpcprovider.js~ethereumrpcprovider#axios",
    "class/src/providers/ethereum/EthereumRPCProvider.js~EthereumRPCProvider.html#instance-member-axios",
    "src/providers/ethereum/EthereumRPCProvider.js~EthereumRPCProvider#axios",
    "member"
  ],
  [
    "src/providers/ethereum/ethereumrpcprovider.js~ethereumrpcprovider#constructor",
    "class/src/providers/ethereum/EthereumRPCProvider.js~EthereumRPCProvider.html#instance-constructor-constructor",
    "src/providers/ethereum/EthereumRPCProvider.js~EthereumRPCProvider#constructor",
    "method"
  ],
  [
    "src/providers/ethereum/ethereumrpcprovider.js~ethereumrpcprovider#generateblock",
    "class/src/providers/ethereum/EthereumRPCProvider.js~EthereumRPCProvider.html#instance-method-generateBlock",
    "src/providers/ethereum/EthereumRPCProvider.js~EthereumRPCProvider#generateBlock",
    "method"
  ],
  [
    "src/providers/index.js",
    "file/src/providers/index.js.html",
    "src/providers/index.js",
    "file"
  ]
]