window.esdocSearchIndex = [
  [
    "chainabstractionlayer/src/providers/bitcoin/bitcoinledgerprovider.js~bitcoinledgerprovider",
    "class/src/providers/bitcoin/BitcoinLedgerProvider.js~BitcoinLedgerProvider.html",
    "<span>BitcoinLedgerProvider</span> <span class=\"search-result-import-path\">chainabstractionlayer/src/providers/bitcoin/BitcoinLedgerProvider.js</span>",
    "class"
  ],
  [
    "chainabstractionlayer/src/providers/bitcoin/bitcoinrpcprovider.js~bitcoinrpcprovider",
    "class/src/providers/bitcoin/BitcoinRPCProvider.js~BitcoinRPCProvider.html",
    "<span>BitcoinRPCProvider</span> <span class=\"search-result-import-path\">chainabstractionlayer/src/providers/bitcoin/BitcoinRPCProvider.js</span>",
    "class"
  ],
  [
    "chainabstractionlayer/src/providers/bitcoin/bitcoinswapprovider.js~bitcoinswapprovider",
    "class/src/providers/bitcoin/BitcoinSwapProvider.js~BitcoinSwapProvider.html",
    "<span>BitcoinSwapProvider</span> <span class=\"search-result-import-path\">chainabstractionlayer/src/providers/bitcoin/BitcoinSwapProvider.js</span>",
    "class"
  ],
  [
    "chainabstractionlayer/src/client.js~client",
    "class/src/Client.js~Client.html",
    "<span>Client</span> <span class=\"search-result-import-path\">chainabstractionlayer/src/Client.js</span>",
    "class"
  ],
  [
    "chainabstractionlayer/src/errors.js~duplicateprovidererror",
    "variable/index.html#static-variable-DuplicateProviderError",
    "<span>DuplicateProviderError</span> <span class=\"search-result-import-path\">chainabstractionlayer/src/errors.js</span>",
    "variable"
  ],
  [
    "chainabstractionlayer/src/providers/ethereum/ethereumledgerprovider.js~ethereumledgerprovider",
    "class/src/providers/ethereum/EthereumLedgerProvider.js~EthereumLedgerProvider.html",
    "<span>EthereumLedgerProvider</span> <span class=\"search-result-import-path\">chainabstractionlayer/src/providers/ethereum/EthereumLedgerProvider.js</span>",
    "class"
  ],
  [
    "chainabstractionlayer/src/providers/ethereum/ethereummetamaskprovider.js~ethereummetamaskprovider",
    "class/src/providers/ethereum/EthereumMetaMaskProvider.js~EthereumMetaMaskProvider.html",
    "<span>EthereumMetaMaskProvider</span> <span class=\"search-result-import-path\">chainabstractionlayer/src/providers/ethereum/EthereumMetaMaskProvider.js</span>",
    "class"
  ],
  [
    "chainabstractionlayer/src/providers/ethereum/ethereumrpcprovider.js~ethereumrpcprovider",
    "class/src/providers/ethereum/EthereumRPCProvider.js~EthereumRPCProvider.html",
    "<span>EthereumRPCProvider</span> <span class=\"search-result-import-path\">chainabstractionlayer/src/providers/ethereum/EthereumRPCProvider.js</span>",
    "class"
  ],
  [
    "chainabstractionlayer/src/providers/ethereum/ethereumswapprovider.js~ethereumswapprovider",
    "class/src/providers/ethereum/EthereumSwapProvider.js~EthereumSwapProvider.html",
    "<span>EthereumSwapProvider</span> <span class=\"search-result-import-path\">chainabstractionlayer/src/providers/ethereum/EthereumSwapProvider.js</span>",
    "class"
  ],
  [
    "chainabstractionlayer/src/errors.js~invalidprovidererror",
    "variable/index.html#static-variable-InvalidProviderError",
    "<span>InvalidProviderError</span> <span class=\"search-result-import-path\">chainabstractionlayer/src/errors.js</span>",
    "variable"
  ],
  [
    "chainabstractionlayer/src/errors.js~invalidproviderresponseerror",
    "variable/index.html#static-variable-InvalidProviderResponseError",
    "<span>InvalidProviderResponseError</span> <span class=\"search-result-import-path\">chainabstractionlayer/src/errors.js</span>",
    "variable"
  ],
  [
    "chainabstractionlayer/src/providers/jsonrpcprovider.js~jsonrpcprovider",
    "class/src/providers/JsonRpcProvider.js~JsonRpcProvider.html",
    "<span>JsonRpcProvider</span> <span class=\"search-result-import-path\">chainabstractionlayer/src/providers/JsonRpcProvider.js</span>",
    "class"
  ],
  [
    "chainabstractionlayer/src/errors.js~noprovidererror",
    "variable/index.html#static-variable-NoProviderError",
    "<span>NoProviderError</span> <span class=\"search-result-import-path\">chainabstractionlayer/src/errors.js</span>",
    "variable"
  ],
  [
    "chainabstractionlayer/src/provider.js~provider",
    "class/src/Provider.js~Provider.html",
    "<span>Provider</span> <span class=\"search-result-import-path\">chainabstractionlayer/src/Provider.js</span>",
    "class"
  ],
  [
    "chainabstractionlayer/src/providers/rpcerror.js~rpcerror",
    "class/src/providers/RpcError.js~RpcError.html",
    "<span>RpcError</span> <span class=\"search-result-import-path\">chainabstractionlayer/src/providers/RpcError.js</span>",
    "class"
  ],
  [
    "chainabstractionlayer/src/errors.js~standarderror",
    "variable/index.html#static-variable-StandardError",
    "<span>StandardError</span> <span class=\"search-result-import-path\">chainabstractionlayer/src/errors.js</span>",
    "variable"
  ],
  [
    "chainabstractionlayer/src/errors.js~unimplementedmethoderror",
    "variable/index.html#static-variable-UnimplementedMethodError",
    "<span>UnimplementedMethodError</span> <span class=\"search-result-import-path\">chainabstractionlayer/src/errors.js</span>",
    "variable"
  ],
  [
    "chainabstractionlayer/src/errors.js~unsupportedmethoderror",
    "variable/index.html#static-variable-UnsupportedMethodError",
    "<span>UnsupportedMethodError</span> <span class=\"search-result-import-path\">chainabstractionlayer/src/errors.js</span>",
    "variable"
  ],
  [
    "chainabstractionlayer/src/providers/bitcoin/bitcoinutil.js~addresstopubkeyhash",
    "function/index.html#static-function-addressToPubKeyHash",
    "<span>addressToPubKeyHash</span> <span class=\"search-result-import-path\">chainabstractionlayer/src/providers/bitcoin/BitcoinUtil.js</span>",
    "function"
  ],
  [
    "chainabstractionlayer/src/providers/bitcoin/bitcoinutil.js~compresspubkey",
    "function/index.html#static-function-compressPubKey",
    "<span>compressPubKey</span> <span class=\"search-result-import-path\">chainabstractionlayer/src/providers/bitcoin/BitcoinUtil.js</span>",
    "function"
  ],
  [
    "chainabstractionlayer/src/crypto.js~ensurebuffer",
    "function/index.html#static-function-ensureBuffer",
    "<span>ensureBuffer</span> <span class=\"search-result-import-path\">chainabstractionlayer/src/crypto.js</span>",
    "function"
  ],
  [
    "chainabstractionlayer/src/providers/ethereum/ethereumutil.js~ensureethformat",
    "function/index.html#static-function-ensureEthFormat",
    "<span>ensureEthFormat</span> <span class=\"search-result-import-path\">chainabstractionlayer/src/providers/ethereum/EthereumUtil.js</span>",
    "function"
  ],
  [
    "chainabstractionlayer/src/providers/ethereum/ethereumutil.js~formatethresponse",
    "function/index.html#static-function-formatEthResponse",
    "<span>formatEthResponse</span> <span class=\"search-result-import-path\">chainabstractionlayer/src/providers/ethereum/EthereumUtil.js</span>",
    "function"
  ],
  [
    "chainabstractionlayer/src/crypto.js~hash160",
    "function/index.html#static-function-hash160",
    "<span>hash160</span> <span class=\"search-result-import-path\">chainabstractionlayer/src/crypto.js</span>",
    "function"
  ],
  [
    "chainabstractionlayer/src/providers/bitcoin/bitcoinutil.js~pubkeyhashtoaddress",
    "function/index.html#static-function-pubKeyHashToAddress",
    "<span>pubKeyHashToAddress</span> <span class=\"search-result-import-path\">chainabstractionlayer/src/providers/bitcoin/BitcoinUtil.js</span>",
    "function"
  ],
  [
    "chainabstractionlayer/src/providers/bitcoin/bitcoinutil.js~pubkeytoaddress",
    "function/index.html#static-function-pubKeyToAddress",
    "<span>pubKeyToAddress</span> <span class=\"search-result-import-path\">chainabstractionlayer/src/providers/bitcoin/BitcoinUtil.js</span>",
    "function"
  ],
  [
    "chainabstractionlayer/src/crypto.js~ripemd160",
    "function/index.html#static-function-ripemd160",
    "<span>ripemd160</span> <span class=\"search-result-import-path\">chainabstractionlayer/src/crypto.js</span>",
    "function"
  ],
  [
    "chainabstractionlayer/src/crypto.js~sha256",
    "function/index.html#static-function-sha256",
    "<span>sha256</span> <span class=\"search-result-import-path\">chainabstractionlayer/src/crypto.js</span>",
    "function"
  ],
  [
    "src/.external-ecmascript.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "src/.external-ecmascript.js~Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "src/.external-ecmascript.js~ArrayBuffer",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~Boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "src/.external-ecmascript.js~DataView",
    "external"
  ],
  [
    "src/.external-ecmascript.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "src/.external-ecmascript.js~Date",
    "external"
  ],
  [
    "src/.external-ecmascript.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "src/.external-ecmascript.js~Error",
    "external"
  ],
  [
    "src/.external-ecmascript.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "src/.external-ecmascript.js~EvalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "src/.external-ecmascript.js~Float32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "src/.external-ecmascript.js~Float64Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~Function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "src/.external-ecmascript.js~Generator",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "src/.external-ecmascript.js~GeneratorFunction",
    "external"
  ],
  [
    "src/.external-ecmascript.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "src/.external-ecmascript.js~Infinity",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "src/.external-ecmascript.js~Int16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "src/.external-ecmascript.js~Int32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "src/.external-ecmascript.js~Int8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "src/.external-ecmascript.js~InternalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "src/.external-ecmascript.js~JSON",
    "external"
  ],
  [
    "src/.external-ecmascript.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "src/.external-ecmascript.js~Map",
    "external"
  ],
  [
    "src/.external-ecmascript.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "src/.external-ecmascript.js~NaN",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~Number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~Object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "src/.external-ecmascript.js~Promise",
    "external"
  ],
  [
    "src/.external-ecmascript.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "src/.external-ecmascript.js~Proxy",
    "external"
  ],
  [
    "src/.external-ecmascript.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "src/.external-ecmascript.js~RangeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "src/.external-ecmascript.js~ReferenceError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "src/.external-ecmascript.js~Reflect",
    "external"
  ],
  [
    "src/.external-ecmascript.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "src/.external-ecmascript.js~RegExp",
    "external"
  ],
  [
    "src/.external-ecmascript.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "src/.external-ecmascript.js~Set",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~String",
    "external"
  ],
  [
    "src/.external-ecmascript.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "src/.external-ecmascript.js~Symbol",
    "external"
  ],
  [
    "src/.external-ecmascript.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "src/.external-ecmascript.js~SyntaxError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "src/.external-ecmascript.js~TypeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "src/.external-ecmascript.js~URIError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "src/.external-ecmascript.js~Uint16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "src/.external-ecmascript.js~Uint32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "src/.external-ecmascript.js~Uint8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "src/.external-ecmascript.js~Uint8ClampedArray",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "src/.external-ecmascript.js~WeakMap",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "src/.external-ecmascript.js~WeakSet",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "src/.external-ecmascript.js~null",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~string",
    "external"
  ],
  [
    "src/.external-ecmascript.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "src/.external-ecmascript.js~undefined",
    "external"
  ],
  [
    "src/client.js",
    "file/src/Client.js.html",
    "src/Client.js",
    "file"
  ],
  [
    "src/client.js~client#_providers",
    "class/src/Client.js~Client.html#instance-member-_providers",
    "src/Client.js~Client#_providers",
    "member"
  ],
  [
    "src/client.js~client#addprovider",
    "class/src/Client.js~Client.html#instance-method-addProvider",
    "src/Client.js~Client#addProvider",
    "method"
  ],
  [
    "src/client.js~client#constructor",
    "class/src/Client.js~Client.html#instance-constructor-constructor",
    "src/Client.js~Client#constructor",
    "method"
  ],
  [
    "src/client.js~client#generateblock",
    "class/src/Client.js~Client.html#instance-method-generateBlock",
    "src/Client.js~Client#generateBlock",
    "method"
  ],
  [
    "src/client.js~client#generatesecret",
    "class/src/Client.js~Client.html#instance-method-generateSecret",
    "src/Client.js~Client#generateSecret",
    "method"
  ],
  [
    "src/client.js~client#generateswap",
    "class/src/Client.js~Client.html#instance-method-generateSwap",
    "src/Client.js~Client#generateSwap",
    "method"
  ],
  [
    "src/client.js~client#getaddresses",
    "class/src/Client.js~Client.html#instance-method-getAddresses",
    "src/Client.js~Client#getAddresses",
    "method"
  ],
  [
    "src/client.js~client#getblockbyhash",
    "class/src/Client.js~Client.html#instance-method-getBlockByHash",
    "src/Client.js~Client#getBlockByHash",
    "method"
  ],
  [
    "src/client.js~client#getblockbynumber",
    "class/src/Client.js~Client.html#instance-method-getBlockByNumber",
    "src/Client.js~Client#getBlockByNumber",
    "method"
  ],
  [
    "src/client.js~client#getblockheight",
    "class/src/Client.js~Client.html#instance-method-getBlockHeight",
    "src/Client.js~Client#getBlockHeight",
    "method"
  ],
  [
    "src/client.js~client#getproviderformethod",
    "class/src/Client.js~Client.html#instance-method-getProviderForMethod",
    "src/Client.js~Client#getProviderForMethod",
    "method"
  ],
  [
    "src/client.js~client#getrawtransactionbyhash",
    "class/src/Client.js~Client.html#instance-method-getRawTransactionByHash",
    "src/Client.js~Client#getRawTransactionByHash",
    "method"
  ],
  [
    "src/client.js~client#gettransactionbyhash",
    "class/src/Client.js~Client.html#instance-method-getTransactionByHash",
    "src/Client.js~Client#getTransactionByHash",
    "method"
  ],
  [
    "src/client.js~client#sendrawtransaction",
    "class/src/Client.js~Client.html#instance-method-sendRawTransaction",
    "src/Client.js~Client#sendRawTransaction",
    "method"
  ],
  [
    "src/client.js~client#sendtransaction",
    "class/src/Client.js~Client.html#instance-method-sendTransaction",
    "src/Client.js~Client#sendTransaction",
    "method"
  ],
  [
    "src/client.js~client#signmessage",
    "class/src/Client.js~Client.html#instance-method-signMessage",
    "src/Client.js~Client#signMessage",
    "method"
  ],
  [
    "src/client.js~client#validateblock",
    "class/src/Client.js~Client.html#instance-member-validateBlock",
    "src/Client.js~Client#validateBlock",
    "member"
  ],
  [
    "src/client.js~client#validatetransaction",
    "class/src/Client.js~Client.html#instance-member-validateTransaction",
    "src/Client.js~Client#validateTransaction",
    "member"
  ],
  [
    "src/client.js~client#version",
    "class/src/Client.js~Client.html#instance-member-version",
    "src/Client.js~Client#version",
    "member"
  ],
  [
    "src/provider.js",
    "file/src/Provider.js.html",
    "src/Provider.js",
    "file"
  ],
  [
    "src/provider.js~provider#client",
    "class/src/Provider.js~Provider.html#instance-member-client",
    "src/Provider.js~Provider#client",
    "member"
  ],
  [
    "src/provider.js~provider#getmethod",
    "class/src/Provider.js~Provider.html#instance-method-getMethod",
    "src/Provider.js~Provider#getMethod",
    "method"
  ],
  [
    "src/provider.js~provider#setclient",
    "class/src/Provider.js~Provider.html#instance-method-setClient",
    "src/Provider.js~Provider#setClient",
    "method"
  ],
  [
    "src/crypto.js",
    "file/src/crypto.js.html",
    "src/crypto.js",
    "file"
  ],
  [
    "src/errors.js",
    "file/src/errors.js.html",
    "src/errors.js",
    "file"
  ],
  [
    "src/index.js",
    "file/src/index.js.html",
    "src/index.js",
    "file"
  ],
  [
    "src/networks.js",
    "file/src/networks.js.html",
    "src/networks.js",
    "file"
  ],
  [
    "src/providers/jsonrpcprovider.js",
    "file/src/providers/JsonRpcProvider.js.html",
    "src/providers/JsonRpcProvider.js",
    "file"
  ],
  [
    "src/providers/jsonrpcprovider.js~jsonrpcprovider#_axios",
    "class/src/providers/JsonRpcProvider.js~JsonRpcProvider.html#instance-member-_axios",
    "src/providers/JsonRpcProvider.js~JsonRpcProvider#_axios",
    "member"
  ],
  [
    "src/providers/jsonrpcprovider.js~jsonrpcprovider#_parseresponse",
    "class/src/providers/JsonRpcProvider.js~JsonRpcProvider.html#instance-method-_parseResponse",
    "src/providers/JsonRpcProvider.js~JsonRpcProvider#_parseResponse",
    "method"
  ],
  [
    "src/providers/jsonrpcprovider.js~jsonrpcprovider#_preparerequest",
    "class/src/providers/JsonRpcProvider.js~JsonRpcProvider.html#instance-method-_prepareRequest",
    "src/providers/JsonRpcProvider.js~JsonRpcProvider#_prepareRequest",
    "method"
  ],
  [
    "src/providers/jsonrpcprovider.js~jsonrpcprovider#constructor",
    "class/src/providers/JsonRpcProvider.js~JsonRpcProvider.html#instance-constructor-constructor",
    "src/providers/JsonRpcProvider.js~JsonRpcProvider#constructor",
    "method"
  ],
  [
    "src/providers/jsonrpcprovider.js~jsonrpcprovider#rpc",
    "class/src/providers/JsonRpcProvider.js~JsonRpcProvider.html#instance-method-rpc",
    "src/providers/JsonRpcProvider.js~JsonRpcProvider#rpc",
    "method"
  ],
  [
    "src/providers/rpcerror.js",
    "file/src/providers/RpcError.js.html",
    "src/providers/RpcError.js",
    "file"
  ],
  [
    "src/providers/rpcerror.js~rpcerror#constructor",
    "class/src/providers/RpcError.js~RpcError.html#instance-constructor-constructor",
    "src/providers/RpcError.js~RpcError#constructor",
    "method"
  ],
  [
    "src/providers/rpcerror.js~rpcerror#status",
    "class/src/providers/RpcError.js~RpcError.html#instance-set-status",
    "src/providers/RpcError.js~RpcError#status",
    "member"
  ],
  [
    "src/providers/rpcerror.js~rpcerror#status",
    "class/src/providers/RpcError.js~RpcError.html#instance-get-status",
    "src/providers/RpcError.js~RpcError#status",
    "member"
  ],
  [
    "src/providers/rpcerror.js~rpcerror#tostring",
    "class/src/providers/RpcError.js~RpcError.html#instance-method-toString",
    "src/providers/RpcError.js~RpcError#toString",
    "method"
  ],
  [
    "src/providers/bitcoin/bitcoinledgerprovider.js",
    "file/src/providers/bitcoin/BitcoinLedgerProvider.js.html",
    "src/providers/bitcoin/BitcoinLedgerProvider.js",
    "file"
  ],
  [
    "src/providers/bitcoin/bitcoinledgerprovider.js~bitcoinledgerprovider#_blockchaininfobaseurl",
    "class/src/providers/bitcoin/BitcoinLedgerProvider.js~BitcoinLedgerProvider.html#instance-member-_blockChainInfoBaseUrl",
    "src/providers/bitcoin/BitcoinLedgerProvider.js~BitcoinLedgerProvider#_blockChainInfoBaseUrl",
    "member"
  ],
  [
    "src/providers/bitcoin/bitcoinledgerprovider.js~bitcoinledgerprovider#_cointype",
    "class/src/providers/bitcoin/BitcoinLedgerProvider.js~BitcoinLedgerProvider.html#instance-member-_coinType",
    "src/providers/bitcoin/BitcoinLedgerProvider.js~BitcoinLedgerProvider#_coinType",
    "member"
  ],
  [
    "src/providers/bitcoin/bitcoinledgerprovider.js~bitcoinledgerprovider#_connecttoledger",
    "class/src/providers/bitcoin/BitcoinLedgerProvider.js~BitcoinLedgerProvider.html#instance-method-_connectToLedger",
    "src/providers/bitcoin/BitcoinLedgerProvider.js~BitcoinLedgerProvider#_connectToLedger",
    "method"
  ],
  [
    "src/providers/bitcoin/bitcoinledgerprovider.js~bitcoinledgerprovider#_derivationpath",
    "class/src/providers/bitcoin/BitcoinLedgerProvider.js~BitcoinLedgerProvider.html#instance-member-_derivationPath",
    "src/providers/bitcoin/BitcoinLedgerProvider.js~BitcoinLedgerProvider#_derivationPath",
    "member"
  ],
  [
    "src/providers/bitcoin/bitcoinledgerprovider.js~bitcoinledgerprovider#_getaddressdetails",
    "class/src/providers/bitcoin/BitcoinLedgerProvider.js~BitcoinLedgerProvider.html#instance-method-_getAddressDetails",
    "src/providers/bitcoin/BitcoinLedgerProvider.js~BitcoinLedgerProvider#_getAddressDetails",
    "method"
  ],
  [
    "src/providers/bitcoin/bitcoinledgerprovider.js~bitcoinledgerprovider#_getamountbuffer",
    "class/src/providers/bitcoin/BitcoinLedgerProvider.js~BitcoinLedgerProvider.html#instance-method-_getAmountBuffer",
    "src/providers/bitcoin/BitcoinLedgerProvider.js~BitcoinLedgerProvider#_getAmountBuffer",
    "method"
  ],
  [
    "src/providers/bitcoin/bitcoinledgerprovider.js~bitcoinledgerprovider#_getfee",
    "class/src/providers/bitcoin/BitcoinLedgerProvider.js~BitcoinLedgerProvider.html#instance-method-_getFee",
    "src/providers/bitcoin/BitcoinLedgerProvider.js~BitcoinLedgerProvider#_getFee",
    "method"
  ],
  [
    "src/providers/bitcoin/bitcoinledgerprovider.js~bitcoinledgerprovider#_getledgerinputs",
    "class/src/providers/bitcoin/BitcoinLedgerProvider.js~BitcoinLedgerProvider.html#instance-method-_getLedgerInputs",
    "src/providers/bitcoin/BitcoinLedgerProvider.js~BitcoinLedgerProvider#_getLedgerInputs",
    "method"
  ],
  [
    "src/providers/bitcoin/bitcoinledgerprovider.js~bitcoinledgerprovider#_getspendingdetails",
    "class/src/providers/bitcoin/BitcoinLedgerProvider.js~BitcoinLedgerProvider.html#instance-method-_getSpendingDetails",
    "src/providers/bitcoin/BitcoinLedgerProvider.js~BitcoinLedgerProvider#_getSpendingDetails",
    "method"
  ],
  [
    "src/providers/bitcoin/bitcoinledgerprovider.js~bitcoinledgerprovider#_gettransactionhex",
    "class/src/providers/bitcoin/BitcoinLedgerProvider.js~BitcoinLedgerProvider.html#instance-method-_getTransactionHex",
    "src/providers/bitcoin/BitcoinLedgerProvider.js~BitcoinLedgerProvider#_getTransactionHex",
    "method"
  ],
  [
    "src/providers/bitcoin/bitcoinledgerprovider.js~bitcoinledgerprovider#_getunspentoutputsforamount",
    "class/src/providers/bitcoin/BitcoinLedgerProvider.js~BitcoinLedgerProvider.html#instance-method-_getUnspentOutputsForAmount",
    "src/providers/bitcoin/BitcoinLedgerProvider.js~BitcoinLedgerProvider#_getUnspentOutputsForAmount",
    "method"
  ],
  [
    "src/providers/bitcoin/bitcoinledgerprovider.js~bitcoinledgerprovider#_getunspenttransactions",
    "class/src/providers/bitcoin/BitcoinLedgerProvider.js~BitcoinLedgerProvider.html#instance-method-_getUnspentTransactions",
    "src/providers/bitcoin/BitcoinLedgerProvider.js~BitcoinLedgerProvider#_getUnspentTransactions",
    "method"
  ],
  [
    "src/providers/bitcoin/bitcoinledgerprovider.js~bitcoinledgerprovider#_ledgerbtc",
    "class/src/providers/bitcoin/BitcoinLedgerProvider.js~BitcoinLedgerProvider.html#instance-member-_ledgerBtc",
    "src/providers/bitcoin/BitcoinLedgerProvider.js~BitcoinLedgerProvider#_ledgerBtc",
    "member"
  ],
  [
    "src/providers/bitcoin/bitcoinledgerprovider.js~bitcoinledgerprovider#constructor",
    "class/src/providers/bitcoin/BitcoinLedgerProvider.js~BitcoinLedgerProvider.html#instance-constructor-constructor",
    "src/providers/bitcoin/BitcoinLedgerProvider.js~BitcoinLedgerProvider#constructor",
    "method"
  ],
  [
    "src/providers/bitcoin/bitcoinledgerprovider.js~bitcoinledgerprovider#getaddresses",
    "class/src/providers/bitcoin/BitcoinLedgerProvider.js~BitcoinLedgerProvider.html#instance-method-getAddresses",
    "src/providers/bitcoin/BitcoinLedgerProvider.js~BitcoinLedgerProvider#getAddresses",
    "method"
  ],
  [
    "src/providers/bitcoin/bitcoinledgerprovider.js~bitcoinledgerprovider#sendtransaction",
    "class/src/providers/bitcoin/BitcoinLedgerProvider.js~BitcoinLedgerProvider.html#instance-method-sendTransaction",
    "src/providers/bitcoin/BitcoinLedgerProvider.js~BitcoinLedgerProvider#sendTransaction",
    "method"
  ],
  [
    "src/providers/bitcoin/bitcoinledgerprovider.js~bitcoinledgerprovider#signmessage",
    "class/src/providers/bitcoin/BitcoinLedgerProvider.js~BitcoinLedgerProvider.html#instance-method-signMessage",
    "src/providers/bitcoin/BitcoinLedgerProvider.js~BitcoinLedgerProvider#signMessage",
    "method"
  ],
  [
    "src/providers/bitcoin/bitcoinrpcprovider.js",
    "file/src/providers/bitcoin/BitcoinRPCProvider.js.html",
    "src/providers/bitcoin/BitcoinRPCProvider.js",
    "file"
  ],
  [
    "src/providers/bitcoin/bitcoinrpcprovider.js~bitcoinrpcprovider#_decoderawtransaction",
    "class/src/providers/bitcoin/BitcoinRPCProvider.js~BitcoinRPCProvider.html#instance-method-_decodeRawTransaction",
    "src/providers/bitcoin/BitcoinRPCProvider.js~BitcoinRPCProvider#_decodeRawTransaction",
    "method"
  ],
  [
    "src/providers/bitcoin/bitcoinrpcprovider.js~bitcoinrpcprovider#generateblock",
    "class/src/providers/bitcoin/BitcoinRPCProvider.js~BitcoinRPCProvider.html#instance-method-generateBlock",
    "src/providers/bitcoin/BitcoinRPCProvider.js~BitcoinRPCProvider#generateBlock",
    "method"
  ],
  [
    "src/providers/bitcoin/bitcoinrpcprovider.js~bitcoinrpcprovider#getblockbyhash",
    "class/src/providers/bitcoin/BitcoinRPCProvider.js~BitcoinRPCProvider.html#instance-method-getBlockByHash",
    "src/providers/bitcoin/BitcoinRPCProvider.js~BitcoinRPCProvider#getBlockByHash",
    "method"
  ],
  [
    "src/providers/bitcoin/bitcoinrpcprovider.js~bitcoinrpcprovider#getblockbynumber",
    "class/src/providers/bitcoin/BitcoinRPCProvider.js~BitcoinRPCProvider.html#instance-method-getBlockByNumber",
    "src/providers/bitcoin/BitcoinRPCProvider.js~BitcoinRPCProvider#getBlockByNumber",
    "method"
  ],
  [
    "src/providers/bitcoin/bitcoinrpcprovider.js~bitcoinrpcprovider#getrawtransactionbyhash",
    "class/src/providers/bitcoin/BitcoinRPCProvider.js~BitcoinRPCProvider.html#instance-method-getRawTransactionByHash",
    "src/providers/bitcoin/BitcoinRPCProvider.js~BitcoinRPCProvider#getRawTransactionByHash",
    "method"
  ],
  [
    "src/providers/bitcoin/bitcoinrpcprovider.js~bitcoinrpcprovider#gettransactionbyhash",
    "class/src/providers/bitcoin/BitcoinRPCProvider.js~BitcoinRPCProvider.html#instance-method-getTransactionByHash",
    "src/providers/bitcoin/BitcoinRPCProvider.js~BitcoinRPCProvider#getTransactionByHash",
    "method"
  ],
  [
    "src/providers/bitcoin/bitcoinrpcprovider.js~bitcoinrpcprovider#sendrawtransaction",
    "class/src/providers/bitcoin/BitcoinRPCProvider.js~BitcoinRPCProvider.html#instance-method-sendRawTransaction",
    "src/providers/bitcoin/BitcoinRPCProvider.js~BitcoinRPCProvider#sendRawTransaction",
    "method"
  ],
  [
    "src/providers/bitcoin/bitcoinswapprovider.js",
    "file/src/providers/bitcoin/BitcoinSwapProvider.js.html",
    "src/providers/bitcoin/BitcoinSwapProvider.js",
    "file"
  ],
  [
    "src/providers/bitcoin/bitcoinswapprovider.js~bitcoinswapprovider#generateswap",
    "class/src/providers/bitcoin/BitcoinSwapProvider.js~BitcoinSwapProvider.html#instance-method-generateSwap",
    "src/providers/bitcoin/BitcoinSwapProvider.js~BitcoinSwapProvider#generateSwap",
    "method"
  ],
  [
    "src/providers/bitcoin/bitcoinutil.js",
    "file/src/providers/bitcoin/BitcoinUtil.js.html",
    "src/providers/bitcoin/BitcoinUtil.js",
    "file"
  ],
  [
    "src/providers/bitcoin/index.js",
    "file/src/providers/bitcoin/index.js.html",
    "src/providers/bitcoin/index.js",
    "file"
  ],
  [
    "src/providers/ethereum/ethereumledgerprovider.js",
    "file/src/providers/ethereum/EthereumLedgerProvider.js.html",
    "src/providers/ethereum/EthereumLedgerProvider.js",
    "file"
  ],
  [
    "src/providers/ethereum/ethereumledgerprovider.js~ethereumledgerprovider#_cointype",
    "class/src/providers/ethereum/EthereumLedgerProvider.js~EthereumLedgerProvider.html#instance-member-_coinType",
    "src/providers/ethereum/EthereumLedgerProvider.js~EthereumLedgerProvider#_coinType",
    "member"
  ],
  [
    "src/providers/ethereum/ethereumledgerprovider.js~ethereumledgerprovider#_connecttoledger",
    "class/src/providers/ethereum/EthereumLedgerProvider.js~EthereumLedgerProvider.html#instance-method-_connectToLedger",
    "src/providers/ethereum/EthereumLedgerProvider.js~EthereumLedgerProvider#_connectToLedger",
    "method"
  ],
  [
    "src/providers/ethereum/ethereumledgerprovider.js~ethereumledgerprovider#_derivationpath",
    "class/src/providers/ethereum/EthereumLedgerProvider.js~EthereumLedgerProvider.html#instance-member-_derivationPath",
    "src/providers/ethereum/EthereumLedgerProvider.js~EthereumLedgerProvider#_derivationPath",
    "member"
  ],
  [
    "src/providers/ethereum/ethereumledgerprovider.js~ethereumledgerprovider#_ledgereth",
    "class/src/providers/ethereum/EthereumLedgerProvider.js~EthereumLedgerProvider.html#instance-member-_ledgerEth",
    "src/providers/ethereum/EthereumLedgerProvider.js~EthereumLedgerProvider#_ledgerEth",
    "member"
  ],
  [
    "src/providers/ethereum/ethereumledgerprovider.js~ethereumledgerprovider#_updatederivationpath",
    "class/src/providers/ethereum/EthereumLedgerProvider.js~EthereumLedgerProvider.html#instance-method-_updateDerivationPath",
    "src/providers/ethereum/EthereumLedgerProvider.js~EthereumLedgerProvider#_updateDerivationPath",
    "method"
  ],
  [
    "src/providers/ethereum/ethereumledgerprovider.js~ethereumledgerprovider#constructor",
    "class/src/providers/ethereum/EthereumLedgerProvider.js~EthereumLedgerProvider.html#instance-constructor-constructor",
    "src/providers/ethereum/EthereumLedgerProvider.js~EthereumLedgerProvider#constructor",
    "method"
  ],
  [
    "src/providers/ethereum/ethereumledgerprovider.js~ethereumledgerprovider#getaddresses",
    "class/src/providers/ethereum/EthereumLedgerProvider.js~EthereumLedgerProvider.html#instance-method-getAddresses",
    "src/providers/ethereum/EthereumLedgerProvider.js~EthereumLedgerProvider#getAddresses",
    "method"
  ],
  [
    "src/providers/ethereum/ethereumledgerprovider.js~ethereumledgerprovider#signmessage",
    "class/src/providers/ethereum/EthereumLedgerProvider.js~EthereumLedgerProvider.html#instance-method-signMessage",
    "src/providers/ethereum/EthereumLedgerProvider.js~EthereumLedgerProvider#signMessage",
    "method"
  ],
  [
    "src/providers/ethereum/ethereummetamaskprovider.js",
    "file/src/providers/ethereum/EthereumMetaMaskProvider.js.html",
    "src/providers/ethereum/EthereumMetaMaskProvider.js",
    "file"
  ],
  [
    "src/providers/ethereum/ethereummetamaskprovider.js~ethereummetamaskprovider#_metamaskprovider",
    "class/src/providers/ethereum/EthereumMetaMaskProvider.js~EthereumMetaMaskProvider.html#instance-member-_metamaskProvider",
    "src/providers/ethereum/EthereumMetaMaskProvider.js~EthereumMetaMaskProvider#_metamaskProvider",
    "member"
  ],
  [
    "src/providers/ethereum/ethereummetamaskprovider.js~ethereummetamaskprovider#_tomm",
    "class/src/providers/ethereum/EthereumMetaMaskProvider.js~EthereumMetaMaskProvider.html#instance-method-_toMM",
    "src/providers/ethereum/EthereumMetaMaskProvider.js~EthereumMetaMaskProvider#_toMM",
    "method"
  ],
  [
    "src/providers/ethereum/ethereummetamaskprovider.js~ethereummetamaskprovider#constructor",
    "class/src/providers/ethereum/EthereumMetaMaskProvider.js~EthereumMetaMaskProvider.html#instance-constructor-constructor",
    "src/providers/ethereum/EthereumMetaMaskProvider.js~EthereumMetaMaskProvider#constructor",
    "method"
  ],
  [
    "src/providers/ethereum/ethereummetamaskprovider.js~ethereummetamaskprovider#getaddresses",
    "class/src/providers/ethereum/EthereumMetaMaskProvider.js~EthereumMetaMaskProvider.html#instance-method-getAddresses",
    "src/providers/ethereum/EthereumMetaMaskProvider.js~EthereumMetaMaskProvider#getAddresses",
    "method"
  ],
  [
    "src/providers/ethereum/ethereummetamaskprovider.js~ethereummetamaskprovider#getblockbynumber",
    "class/src/providers/ethereum/EthereumMetaMaskProvider.js~EthereumMetaMaskProvider.html#instance-method-getBlockByNumber",
    "src/providers/ethereum/EthereumMetaMaskProvider.js~EthereumMetaMaskProvider#getBlockByNumber",
    "method"
  ],
  [
    "src/providers/ethereum/ethereummetamaskprovider.js~ethereummetamaskprovider#gettransactionbyhash",
    "class/src/providers/ethereum/EthereumMetaMaskProvider.js~EthereumMetaMaskProvider.html#instance-method-getTransactionByHash",
    "src/providers/ethereum/EthereumMetaMaskProvider.js~EthereumMetaMaskProvider#getTransactionByHash",
    "method"
  ],
  [
    "src/providers/ethereum/ethereummetamaskprovider.js~ethereummetamaskprovider#sendtransaction",
    "class/src/providers/ethereum/EthereumMetaMaskProvider.js~EthereumMetaMaskProvider.html#instance-method-sendTransaction",
    "src/providers/ethereum/EthereumMetaMaskProvider.js~EthereumMetaMaskProvider#sendTransaction",
    "method"
  ],
  [
    "src/providers/ethereum/ethereummetamaskprovider.js~ethereummetamaskprovider#signmessage",
    "class/src/providers/ethereum/EthereumMetaMaskProvider.js~EthereumMetaMaskProvider.html#instance-method-signMessage",
    "src/providers/ethereum/EthereumMetaMaskProvider.js~EthereumMetaMaskProvider#signMessage",
    "method"
  ],
  [
    "src/providers/ethereum/ethereumrpcprovider.js",
    "file/src/providers/ethereum/EthereumRPCProvider.js.html",
    "src/providers/ethereum/EthereumRPCProvider.js",
    "file"
  ],
  [
    "src/providers/ethereum/ethereumrpcprovider.js~ethereumrpcprovider#_parseresponse",
    "class/src/providers/ethereum/EthereumRPCProvider.js~EthereumRPCProvider.html#instance-method-_parseResponse",
    "src/providers/ethereum/EthereumRPCProvider.js~EthereumRPCProvider#_parseResponse",
    "method"
  ],
  [
    "src/providers/ethereum/ethereumrpcprovider.js~ethereumrpcprovider#generateblock",
    "class/src/providers/ethereum/EthereumRPCProvider.js~EthereumRPCProvider.html#instance-method-generateBlock",
    "src/providers/ethereum/EthereumRPCProvider.js~EthereumRPCProvider#generateBlock",
    "method"
  ],
  [
    "src/providers/ethereum/ethereumrpcprovider.js~ethereumrpcprovider#getaddresses",
    "class/src/providers/ethereum/EthereumRPCProvider.js~EthereumRPCProvider.html#instance-method-getAddresses",
    "src/providers/ethereum/EthereumRPCProvider.js~EthereumRPCProvider#getAddresses",
    "method"
  ],
  [
    "src/providers/ethereum/ethereumrpcprovider.js~ethereumrpcprovider#getblockbynumber",
    "class/src/providers/ethereum/EthereumRPCProvider.js~EthereumRPCProvider.html#instance-method-getBlockByNumber",
    "src/providers/ethereum/EthereumRPCProvider.js~EthereumRPCProvider#getBlockByNumber",
    "method"
  ],
  [
    "src/providers/ethereum/ethereumrpcprovider.js~ethereumrpcprovider#gettransactionbyhash",
    "class/src/providers/ethereum/EthereumRPCProvider.js~EthereumRPCProvider.html#instance-method-getTransactionByHash",
    "src/providers/ethereum/EthereumRPCProvider.js~EthereumRPCProvider#getTransactionByHash",
    "method"
  ],
  [
    "src/providers/ethereum/ethereumswapprovider.js",
    "file/src/providers/ethereum/EthereumSwapProvider.js.html",
    "src/providers/ethereum/EthereumSwapProvider.js",
    "file"
  ],
  [
    "src/providers/ethereum/ethereumswapprovider.js~ethereumswapprovider#generateswap",
    "class/src/providers/ethereum/EthereumSwapProvider.js~EthereumSwapProvider.html#instance-method-generateSwap",
    "src/providers/ethereum/EthereumSwapProvider.js~EthereumSwapProvider#generateSwap",
    "method"
  ],
  [
    "src/providers/ethereum/ethereumutil.js",
    "file/src/providers/ethereum/EthereumUtil.js.html",
    "src/providers/ethereum/EthereumUtil.js",
    "file"
  ],
  [
    "src/providers/ethereum/index.js",
    "file/src/providers/ethereum/index.js.html",
    "src/providers/ethereum/index.js",
    "file"
  ],
  [
    "src/providers/index.js",
    "file/src/providers/index.js.html",
    "src/providers/index.js",
    "file"
  ],
  [
    "src/schema/index.js",
    "file/src/schema/index.js.html",
    "src/schema/index.js",
    "file"
  ]
]